import time

txt = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vitae sapien lorem. Donec hendrerit volutpat finibus. Sed eget vestibulum mi, ut sagittis enim. Cras faucibus tincidunt sem quis aliquet. Quisque id facilisis massa. Phasellus porta mi nisi, quis elementum ipsum vestibulum egestas. Etiam ac justo id lacus euismod pretium. Nunc mattis accumsan accumsan. Nunc maximus, nisi ultricies dictum luctus, arcu sem facilisis mi, condimentum ullamcorper libero massa eu nunc. Vivamus consequat, urna ac molestie luctus, purus nibh venenatis libero, sed lacinia sapien erat tincidunt est. Vestibulum ullamcorper, justo sed faucibus pharetra, ligula leo varius ligula, vel feugiat magna sem eget metus. Etiam pretium cursus egestas. Mauris vulputate nisi vel quam eleifend, ut molestie mi malesuada. Nam porta ex ut hendrerit fermentum.

Phasellus felis arcu, lobortis eget diam ac, fermentum porttitor massa. In varius ac justo ac tempor. In hac habitasse platea dictumst. Maecenas faucibus sapien ac tellus molestie, blandit feugiat turpis tincidunt. Duis sed lacus vel velit tempus feugiat quis a massa. Aenean non justo nisi. Quisque maximus suscipit erat, tempus lobortis lorem. Curabitur eu dolor ac ligula gravida euismod ac a velit. Mauris consectetur at libero vel tincidunt. Integer eu lectus non massa vestibulum porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin gravida justo vitae cursus scelerisque.

Quisque nec dictum purus. Donec in nunc condimentum, maximus leo nec, dictum erat. Phasellus eget augue libero. Sed sed orci libero. Etiam tincidunt lectus scelerisque mauris pulvinar malesuada. Sed non massa posuere, suscipit mi nec, accumsan mi. Nam sit amet accumsan arcu. Morbi efficitur orci eget sapien sodales, eu dictum metus rhoncus. Proin a malesuada nulla, eu euismod lorem. In quis sodales ante. Phasellus luctus viverra euismod. Cras id elit leo. Sed eget lorem eget velit scelerisque eleifend imperdiet id dolor. Fusce non augue ac felis elementum feugiat ac eget ipsum.

Sed sagittis et magna luctus suscipit. Proin sit amet condimentum tellus, non egestas lorem. Curabitur quis lorem in eros rhoncus mattis eget ut nunc. Nulla porttitor, tellus at dictum volutpat, turpis ante pretium sem, sit amet venenatis orci tortor vitae sapien. Etiam nec urna sed augue lobortis lobortis ut sed nibh. Suspendisse accumsan lacinia lobortis. Suspendisse turpis nibh, imperdiet non diam at, elementum gravida velit. In vel mi orci. Sed eget arcu vitae diam malesuada tempor eu at lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla sit amet massa et orci dignissim mollis ut at dui. Praesent nec lorem non nisl maximus molestie sit amet vitae diam. Ut suscipit eros quam, mollis ornare neque vestibulum at. Nulla at erat lacus.

Duis rhoncus quam ut hendrerit placerat. Sed non tempus elit, quis sollicitudin sem. Aliquam aliquet ante vel ex pharetra, ac iaculis libero rhoncus. Curabitur ut arcu metus. Curabitur vulputate, magna quis iaculis sollicitudin, turpis lacus fringilla arcu, vitae ullamcorper augue tellus a arcu. Ut sapien enim, sollicitudin id ornare sed, finibus ac dolor. Morbi tincidunt ac magna at accumsan. Ut dolor ex, porta sagittis convallis eu, accumsan nec turpis. Pellentesque elit dui, fringilla non libero ut, efficitur mollis purus. Ut vitae accumsan massa, ut euismod urna. Curabitur eget quam ut arcu ullamcorper molestie vitae eget risus. Proin feugiat risus eget arcu tempus finibus. Duis elementum nulla dolor, semper tincidunt justo varius ut. Aliquam mollis, erat non tempus egestas, quam elit vestibulum ante, sit amet ultrices eros velit id ex. Etiam quis arcu in eros ullamcorper congue.

Cras a fermentum elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris dapibus pellentesque dolor eget faucibus. Nam sollicitudin tempus urna vel molestie. Aenean quis tristique mauris. Vivamus eget nulla vitae quam varius posuere ut volutpat elit. Proin elementum, mauris nec accumsan commodo, orci tortor volutpat nunc, sit amet hendrerit felis tortor non quam. Integer hendrerit id sapien sodales interdum. Nam arcu nulla, varius in pharetra at, faucibus ac lacus. Ut feugiat ullamcorper enim, eu placerat purus consectetur sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec semper nulla sed justo ultricies, sit amet venenatis nulla cursus.

Vivamus consequat gravida lacinia. Sed interdum bibendum dolor. Pellentesque pretium, tortor quis viverra rhoncus, lorem diam venenatis urna, mollis tristique tellus risus eu libero. Quisque sed euismod odio, at ullamcorper felis. Fusce vel varius turpis. Suspendisse efficitur eros pellentesque rutrum vestibulum. Nullam vel elit eget odio ornare porta vel quis purus. Suspendisse et magna orci.

Duis eleifend ac nunc vel efficitur. Curabitur mollis, sem eu sagittis semper, justo libero ornare purus, eget rhoncus dui ex ac quam. Quisque vitae sapien urna. Aliquam sollicitudin purus eros, eu maximus magna euismod quis. Aliquam venenatis elementum diam ut dapibus. Nullam eu nunc luctus, aliquam est sit amet, gravida est. Donec quis efficitur ex, consectetur tristique nunc. Duis felis eros, tempus in erat a, lacinia consequat felis.

Nunc vitae lorem ut tellus pretium interdum. Etiam eget libero sed felis malesuada porttitor. Quisque aliquam turpis sed enim consectetur, quis sagittis sapien auctor. Aenean metus nisl, semper consequat ultricies eget, accumsan eu mi. Donec viverra laoreet tincidunt. Mauris quis mattis nisi. Quisque diam sapien, congue dapibus elementum in, posuere sed quam. Fusce id nisl quis dolor consectetur molestie luctus et mi. Nam a mollis arcu, ac pretium sapien. Maecenas nec erat vel elit dignissim lobortis sit amet id dui. Sed mollis, risus sed posuere iaculis, lacus purus ullamcorper velit, eu sollicitudin ligula justo non ligula.

Nam a rutrum libero. Aliquam sed felis tempus, suscipit ante et, fermentum ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse tincidunt, ligula iaculis vulputate commodo, mi libero pellentesque sem, sed venenatis nisi libero eget risus. Nulla ultrices est ut aliquet pulvinar. Pellentesque pellentesque vel velit vitae dignissim. Aliquam semper erat faucibus libero tristique convallis. Pellentesque in interdum quam. In non enim porttitor, cursus tellus vel, tristique erat. Cras tempor elit mi, nec rutrum quam luctus eget. Praesent massa eros, molestie a vestibulum vel, suscipit et turpis. Nulla consectetur eros in mi blandit fringilla. Phasellus vitae tempor urna.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec justo in tellus faucibus venenatis quis sit amet sapien. Proin sit amet diam at mi semper dictum. Duis efficitur id nibh id viverra. Integer egestas non metus sed laoreet. Cras facilisis elit mi, eu laoreet ante porttitor ac. Maecenas sapien odio, sollicitudin posuere lacus a, tristique porttitor ante. Aenean tincidunt, velit ac fermentum luctus, diam elit rutrum lectus, id auctor nisl quam ut diam. Sed mattis, risus sit amet hendrerit sodales, tellus dolor ultricies velit, pretium vulputate lectus mi semper magna. Aliquam eleifend venenatis magna, dictum tincidunt justo finibus a. Nulla id ullamcorper nisl, at blandit sapien. Mauris cursus venenatis sagittis.

Praesent tincidunt egestas lacus non condimentum. Proin ullamcorper ultrices tristique. Pellentesque quis varius libero. In tristique tortor id imperdiet iaculis. Sed laoreet porta diam. Maecenas velit sapien, dignissim at odio ac, tempus molestie lorem. Donec accumsan nisi sit amet arcu suscipit semper. Sed sapien est, mollis quis congue nec, accumsan nec ligula. Praesent sollicitudin odio aliquet, vestibulum lorem vitae, ullamcorper metus. Nunc varius fringilla ipsum, nec vestibulum nibh finibus ac. Integer ut velit a enim tempus porta sit amet vel nulla. Aenean nec feugiat turpis. Aenean condimentum magna egestas odio consectetur, vel fringilla ipsum vulputate. Nunc diam elit, pellentesque nec mauris sed, imperdiet ullamcorper tortor.

Vivamus venenatis ante consectetur, porttitor dolor non, consequat nunc. Nulla luctus dictum tellus. Praesent arcu neque, eleifend ac velit in, lacinia iaculis lectus. Vestibulum auctor luctus ipsum, eu hendrerit urna egestas at. Duis justo metus, tristique quis aliquam eget, pharetra eget nisi. Donec metus lacus, dapibus a erat in, accumsan fermentum nibh. Mauris vel suscipit metus. Mauris ac facilisis lorem. Aenean ultrices sem id ex lacinia elementum. Sed scelerisque eros nec nisl semper tincidunt. Nulla neque mauris, viverra et efficitur ut, rhoncus a neque. Fusce posuere purus justo, euismod vestibulum lectus hendrerit vel. Nulla posuere in quam ac convallis. Sed pulvinar sodales feugiat.

Nulla lobortis fringilla arcu, eget interdum ligula eleifend ut. Quisque sollicitudin, massa et ultrices vulputate, arcu lorem dignissim erat, eu egestas risus ex at dolor. Nunc commodo ante at nulla eleifend, eu dictum dui ultrices. Aliquam malesuada lorem a convallis aliquam. Integer ut dolor consequat, efficitur mi quis, ultrices tortor. Duis quis tincidunt augue, vitae ornare metus. In in ligula bibendum, ullamcorper nibh in, porttitor ante.

Phasellus nec pulvinar augue, non ultricies risus. Nullam consectetur pharetra euismod. Duis eu est ligula. Praesent nec nibh quam. Nunc efficitur a turpis sit amet luctus. Etiam a arcu nec quam convallis lobortis nec nec purus. Vivamus vel nibh lobortis, accumsan erat eget, imperdiet felis. Integer nec lectus sed turpis dictum gravida. Nullam cursus pellentesque lacinia.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla eu purus ut congue. Curabitur egestas tincidunt est eget imperdiet. Vivamus tincidunt dui eget elit congue, ut dictum nisl pretium. Fusce quis lorem euismod lectus lobortis tincidunt pharetra sit amet ante. Maecenas quis tristique urna. Suspendisse vel iaculis lectus.

Sed viverra lectus arcu, a scelerisque ligula ultrices ut. Suspendisse eu libero vel nulla eleifend luctus at et dui. Morbi arcu mi, molestie et scelerisque non, egestas eu lectus. Pellentesque eu tortor ac dui varius dignissim nec sed elit. Mauris non turpis justo. Nulla molestie non erat nec tempus. Aliquam sed purus ac sapien auctor volutpat sed ut dui. Vestibulum nisl tellus, tempor sit amet risus sit amet, efficitur convallis massa. Nam at leo bibendum, viverra nisi molestie, euismod orci. Praesent quis purus arcu. Vestibulum laoreet nibh nec lectus maximus, ac tempus quam sollicitudin. Morbi et interdum lorem. Duis ligula nisi, ultrices consequat tellus at, pulvinar ornare mi. Mauris pellentesque rhoncus tristique. Etiam magna eros, accumsan non pellentesque vitae, rhoncus id justo.

Quisque vel ullamcorper neque. Quisque vel ipsum eget risus condimentum ultrices. Proin fringilla quis magna porttitor ornare. Aliquam varius magna fringilla massa luctus elementum id nec nulla. Praesent feugiat, mauris at consequat mollis, nisl lacus condimentum odio, vitae rhoncus magna purus id lorem. Vivamus eget ipsum ut ligula accumsan tempus. Etiam felis justo, iaculis non libero in, cursus vestibulum eros. Phasellus at ullamcorper nibh. Nunc quis nibh vitae justo faucibus maximus.

Nulla sed dolor vitae mauris tempus fermentum. Vestibulum lobortis orci non ullamcorper rhoncus. Maecenas varius consectetur euismod. Morbi iaculis facilisis sapien ut dignissim. Aenean nec ultrices diam. Duis non leo nibh. Nullam mattis diam quis risus egestas iaculis. In ullamcorper urna mauris, quis iaculis risus iaculis at. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur condimentum nisi nisl, nec rutrum purus laoreet vitae. Donec eu lacus dapibus, volutpat ligula quis, elementum dui.

Phasellus quis facilisis lectus. Nam id erat justo. Maecenas aliquet mi sed luctus posuere. Nullam feugiat pharetra ex. Duis rutrum congue erat ut interdum. Quisque commodo, ligula vel fermentum consectetur, nisl lacus efficitur sapien, ac sollicitudin eros mauris at erat. In quis imperdiet velit, ac dapibus ex. In dictum pellentesque elit, eget blandit quam consectetur et. Mauris ultricies magna ac elit aliquet malesuada. Curabitur lobortis arcu non urna cursus, quis sagittis quam fermentum.

Praesent non lorem lectus. Praesent mauris diam, vulputate quis egestas ut, rhoncus et odio. Morbi a dignissim ante. Duis eget semper sem, vitae semper justo. Sed ullamcorper semper dignissim. Ut pulvinar semper urna et porta. Pellentesque aliquam, felis sed feugiat consequat, erat nibh condimentum erat, sit amet congue ex nisi et velit. Mauris ut lacus at mi ultricies faucibus. Proin scelerisque mauris vel lectus sollicitudin finibus feugiat at turpis.

Fusce varius sem nec eros posuere auctor. Proin tempus felis nec ornare eleifend. Nullam vehicula, nibh in scelerisque dictum, lorem orci pellentesque metus, vestibulum lobortis nisi augue quis risus. Curabitur est justo, porta eget elit a, pellentesque commodo ex. Fusce ac gravida erat. Fusce vehicula sodales luctus. Mauris mauris elit, cursus ut elit sit amet, sodales tempus mauris. In blandit consectetur ex, ac malesuada dolor rutrum non. Phasellus ut sapien ullamcorper, ornare risus et, malesuada arcu. Nunc dapibus urna quis elit accumsan, eu maximus odio bibendum. Sed vitae massa mollis, consectetur nisl a, fermentum libero.

Phasellus eu magna vitae justo facilisis malesuada. Sed ornare tellus sed facilisis rutrum. Phasellus vel euismod erat. Pellentesque hendrerit pellentesque nisl, eu malesuada quam bibendum id. Nulla tincidunt erat eu magna egestas, a dapibus nisl luctus. Integer tincidunt vestibulum dolor, vel posuere quam tristique vitae. Maecenas aliquam sodales iaculis. Quisque quis ante scelerisque, egestas ante sollicitudin, sagittis nunc. Sed et molestie purus, quis sagittis orci. Morbi rhoncus nunc a justo consectetur placerat eget ut risus. Sed nunc neque, congue molestie scelerisque quis, vulputate eget sapien. Morbi vehicula libero purus, sit amet placerat elit ornare non. Aliquam eget elementum massa, tempor pretium enim. Nam euismod mauris sit amet erat varius posuere. Nam sed urna vel nibh fermentum luctus.

Etiam ligula odio, porta non finibus vitae, cursus ac magna. Donec arcu diam, dapibus sit amet vestibulum vitae, scelerisque ac eros. Sed hendrerit lectus enim, quis dapibus odio iaculis non. Maecenas vehicula libero ut nulla ultrices, quis tempor nunc lacinia. In feugiat, est sed fermentum gravida, justo mi auctor sapien, placerat dignissim quam diam sit amet eros. Suspendisse vestibulum bibendum luctus. Sed molestie ante at dictum pellentesque. Nam sed sapien turpis. Pellentesque pharetra justo non mi fermentum, accumsan porta sapien ornare. Mauris sit amet vestibulum ante. Phasellus pharetra leo rutrum sem consequat, eu porttitor nisi facilisis. Proin feugiat consequat finibus.

Sed ullamcorper efficitur suscipit. Vivamus fringilla, nisi in euismod tincidunt, nulla erat fermentum elit, at rhoncus est augue a odio. Praesent iaculis maximus enim, vitae feugiat massa ullamcorper in. Cras a luctus ex, et faucibus odio. Etiam maximus, leo non tincidunt consequat, massa ipsum condimentum leo, a mattis arcu lorem nec orci. Cras condimentum, enim vehicula condimentum dignissim, ipsum lacus luctus leo, nec tempus orci tellus ac turpis. Maecenas malesuada posuere bibendum. Fusce mattis, nulla et finibus accumsan, elit libero aliquet tellus, quis volutpat nisl dolor vitae nisi. Suspendisse faucibus, ante quis fermentum suscipit, odio augue commodo ante, quis blandit odio justo eu arcu.

Nulla facilisi. Nunc urna enim, tempus at lorem eu, pellentesque sodales leo. Donec lacinia dignissim lacus quis consectetur. Praesent ut lacinia mi. Nam fermentum metus ac posuere efficitur. In facilisis nibh vel convallis lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras a neque odio. Phasellus nec nunc et leo feugiat consectetur.

Sed vitae augue ac tortor semper maximus. Quisque a eros eleifend, porttitor ex non, convallis tellus. Duis pellentesque tempor augue, eu convallis orci. Aenean accumsan massa sit amet pellentesque fringilla. Nunc egestas, eros pulvinar venenatis porta, est dui varius velit, et cursus elit nunc ac sapien. Integer eu nulla molestie mi laoreet maximus ac sit amet urna. Sed aliquam felis vel ultricies iaculis.

Duis feugiat viverra lorem posuere malesuada. Aliquam ut diam turpis. Nam commodo gravida faucibus. Cras pretium dui sed ex bibendum, non tempor enim tristique. Curabitur viverra nunc eu tempor rutrum. Praesent bibendum id ipsum sit amet porta. Donec auctor lorem id orci blandit venenatis. Etiam ultricies quis tellus ut congue. Sed maximus mi sit amet justo vulputate convallis. Phasellus cursus arcu at lorem suscipit interdum. Curabitur placerat dignissim tincidunt. Mauris lacinia velit arcu, ac feugiat libero cursus sed. Quisque tristique, diam et tempor consequat, dolor nibh placerat sem, a facilisis leo purus at eros.

Ut pretium risus a fermentum volutpat. Duis auctor, felis vel finibus porta, arcu dolor sollicitudin quam, sodales semper eros sem ac justo. Curabitur condimentum massa quis enim facilisis, ac luctus turpis laoreet. Ut condimentum mi eu eros gravida, quis semper ipsum ultrices. Integer vitae enim fermentum, interdum risus et, hendrerit leo. Vivamus at purus elit. Aliquam viverra rhoncus velit eu aliquam. Sed vel orci pretium, suscipit elit at, vehicula sem. Aliquam sit amet faucibus felis.

Fusce interdum urna tempus ipsum cursus aliquet. Phasellus finibus sem enim, id tristique mauris convallis nec. Nullam gravida et augue quis pretium. Sed euismod erat quis sem sagittis dictum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque a commodo odio, sit amet venenatis velit. Morbi blandit augue eu ultrices blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec scelerisque hendrerit arcu at imperdiet. Nullam finibus mollis erat, ut facilisis est. Nulla mi nisl, luctus vitae turpis et, tempor pellentesque ligula. Proin dignissim, orci vel posuere commodo, purus lectus maximus eros, id viverra tellus sapien ut nunc. Proin sapien libero, eleifend rutrum imperdiet et, eleifend id orci. Etiam quis augue ex.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras hendrerit dui turpis, in commodo orci rhoncus eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam mollis tincidunt efficitur. Quisque elementum, eros sit amet cursus tincidunt, nibh est euismod nulla, et interdum velit tellus sollicitudin magna. Cras porta, est a sollicitudin scelerisque, leo erat consectetur risus, at volutpat libero lacus et nibh. In sed est sagittis, fringilla lorem id, elementum tellus. Nam cursus justo eget lacus gravida sollicitudin. Nullam iaculis sed tortor luctus tincidunt.

Ut felis leo, faucibus a massa sed, facilisis pharetra est. Vestibulum viverra odio vitae leo viverra, pellentesque condimentum justo euismod. Sed aliquam massa nisi, tempor dictum velit volutpat in. Sed eget convallis quam, sed ultrices orci. Sed vehicula nisi metus, vel convallis risus porttitor nec. Duis pretium sapien mi, placerat finibus magna venenatis sed. Cras ut imperdiet orci, eget rhoncus est. Pellentesque sed lectus eu massa vulputate molestie. Nullam sit amet tempus massa, vel luctus nulla. Phasellus ligula ligula, euismod a ante eu, suscipit tincidunt lectus. Phasellus quam arcu, tincidunt ut placerat eget, facilisis ut urna. Aliquam erat volutpat. Cras nibh arcu, ultrices eu eleifend in, mattis ut sem. Sed volutpat risus a odio tincidunt malesuada.

Morbi lobortis purus id nunc varius mollis. Sed sit amet pellentesque nunc. Donec eu lacus in ex rutrum tincidunt. Pellentesque elementum nisi sed lacus viverra, eu tincidunt velit dictum. Maecenas tempus risus sed libero feugiat tincidunt. Sed ac pulvinar arcu. Nulla varius tristique dolor, a pulvinar lacus volutpat vel. Aenean sit amet nisi quis nisi auctor cursus sit amet et nibh. Aenean elementum tincidunt sapien sed gravida. Pellentesque condimentum facilisis vestibulum. In id blandit ante, a tempor augue. Vestibulum eget est volutpat, eleifend velit vitae, hendrerit augue. Integer sit amet accumsan dolor, eu dapibus enim. Nullam vitae diam est.

Vivamus nisi velit, egestas in est ac, posuere condimentum orci. Vestibulum arcu justo, facilisis at mauris vitae, vulputate aliquet nisl. Maecenas quis sapien a eros pellentesque pulvinar et sit amet dolor. Curabitur sit amet quam in erat porttitor dictum. Etiam at pellentesque velit, non ullamcorper lorem. Pellentesque orci urna, cursus nec elit a, molestie dictum lorem. Aliquam ligula velit, porttitor ac tortor eget, volutpat pharetra mauris. Pellentesque at neque sed ligula iaculis finibus. Phasellus sed porta eros. Quisque arcu ipsum, molestie et tellus vel, tempus consequat mauris. Pellentesque rhoncus justo sit amet massa tincidunt tincidunt. Pellentesque dignissim sem nec massa blandit ullamcorper non et quam.

Nunc rhoncus ac libero eget mollis. Integer aliquet nulla vel purus pretium, dapibus efficitur neque vulputate. Donec tincidunt magna ac orci placerat cursus. Duis egestas vulputate ligula vel tempus. Donec rutrum ligula commodo sapien dictum tincidunt. Donec pretium vel arcu et ornare. Nam suscipit ornare tortor quis faucibus. Nulla eu congue enim, a gravida risus. Fusce mollis lectus tellus, a finibus purus laoreet vel. Sed semper urna lacus, non aliquet elit vehicula ut. Duis mi arcu, pulvinar ut tincidunt vel, molestie eleifend neque. Ut malesuada semper neque ac rutrum. Quisque fringilla feugiat maximus. Proin vitae tellus quis nulla varius venenatis ut vitae sapien. Curabitur a ligula tempus, euismod enim ac, elementum est.

Fusce purus lorem, porttitor vitae magna et, pretium mattis leo. Maecenas vehicula finibus mauris id tempus. Duis sodales, metus at rutrum sagittis, turpis elit gravida magna, in egestas leo urna ultrices nisi. Nunc magna ligula, dictum at velit a, faucibus auctor tellus. Vivamus sit amet pellentesque augue. Vestibulum enim magna, posuere scelerisque tortor id, imperdiet lacinia dolor. Duis vestibulum mauris dolor, at euismod felis varius ut. Aliquam placerat ut ligula in ultricies. Nulla facilisi. Pellentesque lectus mi, semper sit amet accumsan at, porta sed dolor. Integer congue eu velit ut varius.

Vestibulum mauris nisi, posuere ut eros ac, maximus commodo mi. Integer maximus arcu et mauris dictum, ac sodales eros tempor. Nam efficitur lacus a risus molestie facilisis. Sed fermentum tristique diam eget fringilla. Morbi consectetur, metus in sodales commodo, dui felis finibus lorem, vel finibus ante libero vitae lectus. Sed massa elit, aliquet ac nisl eu, congue pulvinar nulla. Sed euismod maximus ipsum, dictum suscipit sapien dapibus et. Nam elementum luctus metus eget interdum. Quisque fermentum fringilla est, vitae ullamcorper augue commodo in. Fusce quis faucibus metus. Nullam eu posuere libero, sed ullamcorper erat. Phasellus eget elit mi. Donec malesuada, dolor ac rhoncus varius, magna ante accumsan augue, at finibus erat diam vestibulum tellus. Integer commodo eu quam porta condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse ligula nunc, volutpat sit amet nibh et, consequat hendrerit purus.

Praesent a tristique elit, aliquam blandit ante. Nulla scelerisque gravida dapibus. Vivamus malesuada tortor neque, ut posuere neque fringilla sodales. Vivamus eu lacus a leo venenatis volutpat. Proin cursus quam eu libero egestas, vel consequat ante sodales. Ut malesuada vitae erat sit amet egestas. Cras tempor lectus sed maximus pretium. Donec pellentesque sapien et ligula suscipit euismod. Donec sed ligula eu nisi malesuada sodales.

In metus nibh, tristique vitae dictum id, lacinia vel ante. Fusce blandit eget nisl ut interdum. Aenean sed diam vel est mollis tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. In tincidunt auctor interdum. Vivamus aliquam tincidunt hendrerit. Praesent mollis laoreet auctor. Proin dolor neque, sagittis eu vehicula a, finibus ut lectus. Etiam fermentum vulputate iaculis.

Mauris luctus condimentum neque eu varius. Donec risus est, porta id nulla nec, posuere volutpat lorem. In finibus in enim eu congue. Aliquam condimentum ipsum vel lorem placerat mollis. Maecenas efficitur dolor id ligula lacinia pretium. Curabitur ullamcorper interdum elit. Quisque quis pretium erat, a iaculis dolor.

Duis sit amet volutpat ex. Nunc fermentum arcu et nunc dapibus, sed fringilla libero aliquam. Nulla facilisi. Suspendisse consectetur erat id pellentesque rhoncus. Proin porta laoreet nibh et porta. Pellentesque ac pretium metus, in efficitur lorem. Aenean quis lectus tempus, accumsan sapien quis, ullamcorper arcu. Ut eget vulputate lacus. Mauris at sapien pulvinar, tempus erat eget, laoreet neque. Nullam pharetra nibh nec turpis elementum, quis accumsan leo congue.

Vestibulum feugiat tincidunt elit et mattis. Ut sit amet dignissim turpis. Donec quis eros vestibulum, sollicitudin tortor ac, mollis eros. Donec mattis, quam nec consectetur sodales, odio magna commodo lacus, ut ullamcorper lorem metus eu justo. Nullam mattis justo ut ligula pharetra, nec rutrum metus blandit. Duis sed pulvinar justo, id congue leo. Nam eu sem magna. Duis ullamcorper euismod nisi eu aliquam. In nisi tellus, aliquet eu urna et, mattis maximus nunc. Duis in tempor justo.

Ut laoreet, nibh eu lacinia cursus, ex diam lobortis elit, in pretium eros nulla sit amet ex. Morbi non aliquet ex. Phasellus mollis, tellus at euismod mollis, ipsum ex bibendum ligula, ut sollicitudin enim libero mattis erat. Quisque euismod felis eu rutrum tincidunt. Aliquam iaculis porta sem vitae imperdiet. Donec sed vulputate dolor. Fusce pellentesque et est nec suscipit. Nullam mi dolor, vulputate sit amet velit eget, lobortis sagittis augue. Suspendisse in consectetur arcu. Aliquam in nunc eu sem accumsan porta. Aenean vel varius odio. Nam ultrices euismod urna, eu tincidunt ligula elementum quis. Donec posuere erat eu arcu scelerisque tempor. Nullam non arcu laoreet, elementum lorem at, suscipit velit. Mauris lobortis ipsum eget lectus finibus lobortis. Vivamus imperdiet, nibh in egestas mattis, odio arcu pharetra justo, ac volutpat ex nibh a est.

Vivamus sed maximus lectus. Donec congue dolor id volutpat efficitur. Aliquam maximus, nunc at commodo mattis, mi erat porttitor tellus, ac mollis elit velit id metus. Aliquam vitae felis justo. Phasellus sit amet aliquet urna. Nam facilisis felis nec erat feugiat, vitae viverra justo varius. Praesent ut viverra massa. Suspendisse vitae sapien et ex lacinia ultrices quis in erat. Morbi gravida venenatis neque, ac molestie justo vulputate vel.

Integer varius nulla sodales elit aliquam vehicula. Proin eleifend lorem eget sapien pulvinar ultrices. Quisque ultrices neque justo, sed cursus sapien gravida non. Aenean a quam nulla. Aenean ultrices finibus iaculis. Nulla faucibus augue sit amet nisl eleifend, id rhoncus nunc facilisis. Maecenas eu elit id orci feugiat faucibus in nec sapien. Aenean malesuada odio ac sapien interdum fermentum. Integer tempor dui est, suscipit semper orci luctus et. Pellentesque mattis magna fermentum, aliquam massa varius, malesuada eros.

Nunc massa enim, convallis non fringilla in, maximus eu neque. Praesent placerat mi id luctus porta. Cras semper vulputate tortor, vitae pretium arcu vulputate nec. Ut at ullamcorper lorem. Maecenas vel lorem commodo, varius velit id, tempus justo. Aliquam a magna fringilla erat consequat fringilla quis quis enim. Maecenas porttitor congue felis, id sagittis massa tincidunt eu. Quisque euismod velit id ex egestas, nec dignissim est varius. Nulla eget velit sit amet est convallis dictum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque molestie faucibus imperdiet. Fusce sagittis eros libero. Donec auctor varius cursus. Donec efficitur in quam vel consectetur. Nulla ut accumsan libero. Donec rhoncus condimentum augue in venenatis.

Pellentesque sit amet ultrices metus, ac feugiat lacus. Vestibulum vitae vestibulum massa. Praesent consequat, nibh id sagittis sodales, dolor magna eleifend orci, at tempus ex massa a neque. Sed iaculis ultrices diam, ut elementum metus laoreet id. Integer mattis viverra ipsum eget convallis. Pellentesque vitae sem lorem. Vestibulum blandit purus quis ligula fringilla, eget viverra odio pharetra. Nulla ac metus posuere sem condimentum egestas vitae in diam.

Morbi convallis odio vel tellus porta pretium. Fusce ac sapien porta, condimentum lectus et, dapibus metus. Nam nec massa quis nulla finibus finibus. Sed euismod magna odio, non consequat urna eleifend et. Donec lobortis nunc tellus. In hac habitasse platea dictumst. Integer in neque et metus scelerisque mollis eget non lectus. Nulla fermentum in lorem in facilisis. Aliquam vitae odio suscipit, posuere odio et, aliquam velit. Maecenas auctor sem et pulvinar elementum. Maecenas tristique, nibh at finibus ornare, ligula lacus vestibulum sem, in fermentum lacus magna et lorem.

Nunc blandit magna vitae arcu condimentum efficitur. Mauris pharetra leo efficitur lacinia sollicitudin. Cras est magna, volutpat nec facilisis at, faucibus ut tortor. In nec lacus diam. Ut massa tellus, dictum sit amet feugiat at, pharetra non odio. Duis at elit pharetra, consectetur ante eu, suscipit lorem. Quisque sagittis, quam sed lobortis congue, augue nisl vestibulum nisi, at accumsan augue justo nec erat. Duis dui justo, feugiat sit amet ante eu, gravida pulvinar sapien. Ut sed erat tempus, scelerisque massa vitae, sodales enim.

Phasellus sapien lacus, hendrerit in justo et, blandit lacinia lorem. Vivamus ex purus, lacinia pharetra venenatis ac, lobortis et eros. Duis elit quam, porta eu volutpat eu, congue eu leo. Maecenas consequat auctor augue, a pellentesque risus euismod sed. In hac habitasse platea dictumst. Integer vitae viverra erat. Praesent feugiat nulla non diam aliquam venenatis.

Ut sit amet eros fermentum, malesuada lorem eget, porta lorem. Phasellus in neque eget velit semper vehicula quis non libero. Donec lobortis dapibus faucibus. Curabitur porta risus tellus, vitae iaculis dolor iaculis ac. Quisque semper bibendum tempor. Nunc sed risus arcu. Cras ut ante a libero ornare venenatis at vitae mauris. Nullam ut ultrices enim, eget vestibulum metus. Suspendisse ac laoreet orci, vel porttitor urna. Aliquam volutpat at ligula hendrerit cursus. Curabitur auctor nec lorem tincidunt placerat. Integer in ipsum enim. Etiam et tortor eros. Sed sapien lectus, iaculis in viverra vitae, sagittis volutpat ipsum.

Integer dictum diam ac ipsum tempus viverra. Fusce ac aliquet libero. Maecenas pharetra eros nunc, ut aliquam enim efficitur ac. Vivamus maximus massa tortor, a maximus urna vestibulum non. Mauris dignissim gravida vestibulum. Pellentesque luctus accumsan est, id iaculis eros facilisis non. Cras nec leo pharetra ligula malesuada bibendum non id ipsum.

Etiam consequat pharetra diam eu mattis. Etiam mollis tellus nibh. Quisque nibh mi, accumsan non orci a, pulvinar sagittis mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent at nulla ut enim lobortis euismod. Nunc sollicitudin auctor fringilla. Maecenas accumsan consequat justo dignissim consectetur. Nunc tempor risus vitae neque porta, et consequat est tincidunt. Cras scelerisque quis urna vitae mattis. Phasellus vitae eros posuere, auctor mi et, cursus quam. Duis elementum massa erat, a maximus risus viverra vitae. Nulla eu mauris ac tellus dignissim porta nec sit amet orci. Pellentesque aliquam ultrices sapien, id feugiat justo bibendum vitae. Cras eu nunc magna. Nunc tristique luctus mollis.

Phasellus semper quam eget mi laoreet, porta accumsan sapien posuere. Aliquam placerat placerat maximus. Curabitur sed lectus feugiat, efficitur sem in, egestas augue. In enim sapien, euismod eu felis nec, egestas condimentum ex. Aenean risus odio, euismod et auctor nec, varius id quam. Donec imperdiet nulla in nunc vulputate elementum. Praesent id tristique sem. In augue ante, malesuada id ornare a, scelerisque at felis. Maecenas iaculis, justo quis varius rhoncus, massa nisl egestas quam, nec rhoncus mauris est ut justo.

Fusce facilisis justo justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ornare accumsan purus, vitae interdum magna. Etiam consequat tortor non lorem maximus fringilla. Aenean euismod, elit sed sodales congue, eros ante porta ligula, in bibendum felis velit ac odio. Donec mauris magna, interdum nec lacinia et, facilisis vitae sapien. Praesent aliquet ultrices aliquet. Vivamus nec elit volutpat, tempor nulla id, viverra nulla. Duis eu enim augue. Aliquam malesuada eros tincidunt risus commodo bibendum. Donec imperdiet est elit, sed commodo justo interdum eget. Etiam semper magna eget massa dapibus ultricies. Sed scelerisque euismod lacus, eget dignissim neque cursus scelerisque. Phasellus ornare mollis ullamcorper.

Integer in blandit lacus, id aliquam eros. Donec tincidunt sem id neque pulvinar, sit amet iaculis lacus posuere. Proin aliquet, sapien vel luctus faucibus, erat purus consectetur libero, quis eleifend lorem purus nec felis. Donec augue risus, sagittis viverra sagittis sodales, bibendum in nibh. Vestibulum interdum dui id felis facilisis, at scelerisque dui consectetur. Sed quis nisi eget felis mattis molestie. Etiam pretium orci id ex lobortis, non pretium orci mattis. Curabitur vitae congue ex. Praesent quis odio arcu. Aenean ultrices maximus diam et scelerisque. Nulla accumsan neque eu mi consectetur, quis porta risus bibendum. Morbi varius varius ligula at semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce faucibus quam nec augue porttitor, ac lobortis sem tincidunt. Praesent volutpat vitae leo a venenatis.

Quisque tortor urna, egestas sit amet felis eu, aliquet congue leo. Curabitur fermentum, tortor vel pretium tincidunt, nisi purus pellentesque ligula, eu lobortis ligula tellus ac nibh. Mauris dapibus ligula vitae diam tempor, sed laoreet neque fringilla. Quisque enim sem, convallis vel erat id, tristique volutpat erat. Nam et dictum mi. Phasellus viverra posuere ex, quis bibendum ex convallis eget. Pellentesque fringilla, augue vitae porttitor porta, augue dolor rutrum quam, eu accumsan metus lectus vitae tortor. Suspendisse id purus quis leo facilisis laoreet id vitae tortor. Duis eleifend imperdiet mi sit amet egestas. Vestibulum rhoncus gravida ornare. Pellentesque malesuada justo ac lobortis rhoncus. Proin quam elit, dapibus at iaculis eget, hendrerit vel nisi. Curabitur at neque blandit, vehicula tortor id, tristique lorem. Donec scelerisque tellus vel arcu varius consectetur. Pellentesque nec sapien ac enim imperdiet iaculis a eget lacus. In lacinia diam eu sem finibus imperdiet.

Phasellus pretium, enim vitae egestas pellentesque, metus mauris mollis sapien, eu ultricies purus velit in massa. Vestibulum eget venenatis nibh, vitae laoreet urna. Sed vel tincidunt est. Pellentesque finibus dui sit amet risus imperdiet, eu maximus orci eleifend. Donec non semper tortor. Curabitur quis facilisis sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a eros sit amet nunc laoreet tempus.

Mauris a odio consectetur, egestas turpis vel, sodales libero. Nullam semper metus vitae augue ullamcorper, et dictum magna molestie. Nulla facilisi. Aliquam vitae metus ultrices, sollicitudin mi eget, lacinia enim. Sed eget convallis ex. Nullam condimentum risus ac pharetra vulputate. Praesent semper, neque vitae malesuada placerat, dui mauris maximus mi, eget interdum sapien ipsum ac mi. Ut et lacus eu massa varius dapibus ac vitae orci. Phasellus eleifend imperdiet neque, vel venenatis diam auctor nec. Curabitur et magna nunc. Nulla quam augue, posuere eu tortor imperdiet, vulputate ultrices elit. Fusce sodales consectetur hendrerit. Nullam ante odio, vestibulum at orci et, porttitor euismod nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Morbi in lorem id lectus facilisis imperdiet sollicitudin non orci. Nunc vel massa metus. Nullam in ex varius, sodales ligula quis, pretium massa. Aenean convallis quis tellus et molestie. Duis sit amet iaculis purus. Phasellus blandit mauris nisl, ac vestibulum eros aliquet et. Aenean dapibus varius ipsum ut posuere.

Sed nec malesuada mauris. Vivamus sit amet justo consequat, congue tortor vitae, suscipit dolor. Duis dictum mauris vel aliquet ultricies. Curabitur consequat sapien at dui aliquet, ut efficitur justo scelerisque. Etiam facilisis mauris vitae scelerisque ullamcorper. Mauris eleifend finibus felis, posuere hendrerit leo commodo et. Etiam finibus finibus urna, sit amet suscipit purus congue vel. Morbi vitae venenatis turpis.

Fusce quis faucibus ante. Nulla fringilla sem a neque tristique scelerisque. In vitae lectus mauris. Aenean consectetur rhoncus lectus id tempus. Proin vitae eleifend enim. Nullam vestibulum dapibus scelerisque. Nulla facilisi. Pellentesque vehicula, lectus quis aliquet porta, eros leo venenatis orci, eu hendrerit massa nisi eu sapien. Mauris vestibulum placerat urna, nec pharetra quam feugiat ut. Nunc aliquet sodales augue nec interdum. Donec lorem ex, convallis eu lobortis ut, tincidunt in magna. Proin eu ligula vitae tellus feugiat consequat. Aenean orci magna, semper vitae posuere sed, pharetra eget erat. Phasellus feugiat sapien non lacus venenatis tincidunt. Sed porta nisi vitae elit pellentesque, in facilisis erat convallis.

Mauris eu porta turpis. Nam eget efficitur est, eget lacinia justo. Phasellus laoreet nisi massa. Vestibulum semper, leo in porttitor vestibulum, tortor leo finibus purus, ac varius justo mauris at leo. Nam aliquam ac eros non ullamcorper. Cras lectus tellus, mattis eu est in, viverra mollis purus. Proin fermentum blandit lacus, quis vestibulum arcu facilisis eget. Vestibulum pulvinar mattis interdum. Suspendisse dolor nibh, suscipit ut arcu et, facilisis facilisis est. Donec sit amet sapien nibh. Duis posuere neque eu cursus tempus. Suspendisse massa erat, semper vitae orci sed, sodales dignissim odio.

Nunc eleifend scelerisque diam eu pretium. Praesent condimentum finibus purus sit amet aliquet. Integer felis erat, convallis ac commodo et, vestibulum et dolor. Nullam ultricies sodales ligula eu ornare. Donec eget felis a est pellentesque ultricies. Cras eget mauris sit amet nibh iaculis ornare. Sed ultricies, arcu nec maximus accumsan, ante ipsum tempus ex, vitae varius metus tellus sed sapien. Mauris convallis nec libero non viverra. Quisque justo nisi, sollicitudin at velit id, egestas luctus sapien. Nam ultricies ipsum non tempor tristique. Nullam ullamcorper ante id elit bibendum tincidunt pretium non lorem. Suspendisse nunc dui, semper quis metus bibendum, vulputate laoreet ante. Maecenas suscipit justo quam, eleifend dictum lorem molestie ut.

Ut pellentesque aliquam vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam vestibulum dui et velit interdum ullamcorper. Curabitur facilisis euismod metus non suscipit. Fusce dolor arcu, placerat quis vehicula vel, iaculis pretium metus. Donec vulputate nulla at elementum pretium. Pellentesque eu eros enim. Nam vulputate, magna non porta tempor, nibh mi fermentum quam, quis molestie urna nunc sed quam. Phasellus molestie a quam vitae dictum.

Vestibulum suscipit accumsan dui, consectetur tempor lacus faucibus nec. Phasellus eget risus tincidunt, lobortis tortor rutrum, aliquam mauris. Ut venenatis lacus imperdiet neque tincidunt, et scelerisque diam fringilla. Phasellus quis dignissim odio. Suspendisse id lorem tincidunt urna bibendum egestas at id enim. Curabitur tempus mollis tellus, eget lobortis felis efficitur id. Fusce sed tortor erat. Aliquam fermentum rutrum enim a tristique. Praesent iaculis, risus non congue accumsan, nulla elit semper odio, ut porta ex ex non nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus orci tellus, accumsan ut sagittis vitae, pellentesque at leo.

Sed sed felis eu turpis tempor euismod non non ante. Vestibulum ultricies hendrerit sapien a tincidunt. Fusce tempus neque erat, quis cursus ipsum interdum eget. Ut ultrices elementum risus, quis pellentesque tellus ultrices sed. Praesent et urna leo. Sed magna augue, auctor a interdum et, facilisis nec purus. Pellentesque tempor quam nibh, quis faucibus leo venenatis ut. Etiam sollicitudin, odio quis consectetur iaculis, tellus nunc rhoncus ex, vitae tempor turpis dui ut est. Nam nibh massa, pharetra at leo quis, pharetra rutrum est. Aliquam id erat ac diam sagittis dictum a eu justo. Phasellus id volutpat nisl, id finibus leo. Proin non mi id nunc laoreet mollis. Pellentesque iaculis rhoncus ipsum, id sagittis lectus porta a. Donec orci velit, pretium sit amet massa et, egestas faucibus mauris. Integer quis quam justo. Quisque vitae nibh at sapien aliquet blandit nec nec augue.

Cras sit amet tortor elit. Donec dictum enim eget orci auctor, at malesuada lorem vehicula. Duis ornare massa ac lacus venenatis varius. Nam placerat, est quis bibendum tempus, metus nibh lacinia urna, eget blandit magna enim quis quam. Suspendisse lobortis, nibh maximus varius interdum, risus nisl varius est, ut finibus augue magna nec magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rutrum turpis eget est ornare tempus. Sed sed sapien a massa mollis porta in sit amet risus. Curabitur quis varius ex. Aliquam non orci ultrices felis auctor placerat. Curabitur tortor purus, maximus ac augue ut, interdum rutrum tortor. Nulla sagittis id enim ut sagittis. Sed et risus eu arcu malesuada porta ut sed nibh. Quisque augue lorem, finibus sit amet consectetur varius, rhoncus at nunc.

Nunc semper ligula velit, et semper felis efficitur quis. Duis in nisl tellus. Morbi ut ultrices neque. Curabitur tincidunt a nibh a efficitur. Pellentesque tortor arcu, aliquam vel dui vel, ullamcorper accumsan erat. In maximus cursus nisi ut consequat. Duis urna felis, laoreet a suscipit quis, placerat vel purus. Fusce ornare arcu nec dui pharetra cursus nec nec erat. Mauris convallis diam purus, at aliquam nisi hendrerit et. Proin ultricies aliquam suscipit. Mauris sodales neque id sem gravida mattis. Pellentesque lobortis, arcu sit amet congue molestie, nisi ligula feugiat leo, vitae accumsan sem felis a lectus.

Vivamus quis nisi quam. Etiam consequat sapien at ipsum aliquam condimentum. Maecenas pretium enim vitae arcu volutpat egestas. Vestibulum ultrices eu nibh id fringilla. Vestibulum aliquet blandit purus ut posuere. Proin neque odio, varius ut rutrum at, porttitor ut ligula. Praesent placerat congue porta. Morbi eu vehicula turpis, eu ornare sapien. Sed vel maximus elit.

Nunc laoreet orci at dui pretium, vitae viverra justo vestibulum. Cras eu scelerisque tortor, et vestibulum sapien. Morbi porttitor, sapien quis laoreet ultricies, ipsum nisi fermentum ante, eget congue ex magna vitae nisi. Donec ut est ipsum. Fusce interdum metus elit, sit amet bibendum sem ornare vitae. Sed velit turpis, finibus nec sodales eu, eleifend ac ligula. Nunc rhoncus aliquet tellus, sed bibendum justo placerat sed. Etiam neque enim, rhoncus quis sodales eget, faucibus vel nibh. Duis et dapibus eros.

Nunc sagittis iaculis mollis. Ut id eros tempor, pretium quam consequat, rhoncus nisl. Integer eu neque arcu. Nullam egestas auctor accumsan. Phasellus viverra eget ligula quis sagittis. Donec metus nisi, gravida pharetra congue nec, cursus sit amet ipsum. Vestibulum a sollicitudin nulla. Suspendisse ipsum nisi, ornare vitae nibh in, lobortis consequat urna. Cras congue lacus et enim luctus, sit amet laoreet diam congue. Fusce interdum lorem vitae congue tincidunt. Sed lacus nulla, laoreet quis tincidunt in, fermentum eget eros. Donec euismod orci varius, cursus lorem ut, aliquet eros.

Proin ut ornare leo. Nam fringilla rutrum sem ut gravida. Praesent sollicitudin odio enim, interdum ultricies orci mattis a. Donec ipsum orci, blandit et diam a, imperdiet mattis lorem. Nunc at enim eget diam interdum luctus. Sed feugiat libero elit, a pulvinar dolor vulputate quis. Praesent tincidunt imperdiet commodo. Donec orci mauris, tincidunt sed nisl in, pulvinar interdum purus. Suspendisse rutrum pharetra augue, at dapibus neque tincidunt nec. Ut viverra, lorem in viverra pretium, felis magna hendrerit massa, non ultrices justo urna id ante. Nulla sagittis pharetra sem, vel facilisis enim cursus nec. Fusce elementum enim tristique ipsum elementum iaculis. Sed molestie, sapien vitae viverra tempus, ligula neque tempor odio, a maximus est urna eu neque. Morbi interdum porta molestie.

Suspendisse sollicitudin metus ut mauris posuere auctor id a orci. Nulla tempor rhoncus enim eget rhoncus. Cras mattis, lectus a finibus viverra, mauris nulla interdum turpis, ac commodo libero dui non massa. Praesent lobortis odio ac nisi consequat tristique. Nulla vitae magna quis velit pretium varius quis in libero. Pellentesque ultrices tincidunt risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor sem erat. Nulla eget elit magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Duis in purus dapibus, luctus mauris vel, cursus enim. Nulla malesuada, lorem vel vehicula accumsan, lorem quam pretium metus, a tempor nibh neque id dui. Donec id tincidunt odio. Mauris nec ex ornare, scelerisque dolor vitae, consequat ex. Donec faucibus risus nec ante aliquet commodo. Cras eleifend fermentum nisl sit amet dapibus. Proin dui dolor, convallis ac feugiat vehicula, hendrerit id nisl.

Donec dictum commodo vulputate. Morbi sem orci, commodo ut turpis ac, mattis faucibus urna. Fusce nec consectetur velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. In ac elementum lorem. Nunc ex purus, aliquam sit amet semper at, ultrices congue orci. Nunc aliquam egestas ex id volutpat. Morbi fringilla, lectus vel pulvinar euismod, risus tellus convallis dolor, sed auctor dui lorem in diam. Integer et nunc nibh. Phasellus posuere ultrices malesuada. In finibus, purus vitae volutpat finibus, orci nunc consequat enim, at tincidunt justo est non enim. Aenean efficitur mi eu lorem fermentum, sed tristique justo elementum. Integer dui elit, fringilla quis dapibus eu, hendrerit quis risus. Ut maximus diam a nisi mattis, eu pharetra lorem varius.

Integer scelerisque, purus at molestie varius, elit erat tincidunt urna, in laoreet mauris magna suscipit felis. Vestibulum aliquet, felis a sodales fringilla, elit lacus dignissim odio, vitae congue diam felis in ante. Cras condimentum lorem vitae feugiat accumsan. Maecenas vel leo libero. Sed nec metus id nunc sagittis rutrum non eu lorem. Morbi posuere purus erat, sit amet molestie mauris elementum id. Ut posuere leo vitae nisl imperdiet, a ultricies massa mattis. Cras blandit iaculis aliquet. Etiam rutrum, nulla in feugiat vehicula, nisi mauris sagittis orci, ut sagittis tortor quam nec mi. Duis nec urna diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sit amet vestibulum nunc.

Nunc metus lectus, bibendum vitae felis ut, pulvinar tempor tellus. Sed facilisis, mi ac ultricies rutrum, leo neque ultrices nunc, vel laoreet dolor ante vitae justo. Donec ultrices euismod orci sed sollicitudin. Nullam maximus ipsum luctus porttitor vehicula. Curabitur a ligula vitae dolor convallis sodales. Etiam lectus magna, euismod eu mi vitae, congue tincidunt erat. Nam blandit, arcu eget venenatis lacinia, sem ex venenatis lacus, quis sollicitudin nisl tellus ut neque. Quisque sed efficitur nibh, luctus mollis ipsum. Duis suscipit ligula sit amet eros blandit sollicitudin. Phasellus sed blandit ex.

Nullam volutpat nec elit et efficitur. Phasellus cursus quam eget scelerisque porttitor. Proin ac diam metus. Praesent dapibus orci vitae neque rhoncus, sit amet accumsan felis semper. Donec in lacus ac tortor tempus pharetra. Nam vel erat vulputate, pellentesque mi quis, mollis mauris. Duis pulvinar neque eget accumsan elementum. Ut sit amet vehicula mauris. Vivamus accumsan auctor quam. Nullam rhoncus justo condimentum ante semper, non euismod elit aliquet. Vestibulum ullamcorper dui mauris, non vulputate ex cursus ut. Vivamus tellus est, aliquam nec est sed, eleifend cursus orci. Maecenas feugiat lacus elit, eget bibendum nibh volutpat ac. Fusce leo risus, dapibus et vehicula eget, laoreet eget nulla. Ut semper ipsum ante, a bibendum diam facilisis nec.

Cras interdum pretium lectus, eu laoreet turpis finibus tincidunt. Sed massa erat, luctus quis massa vel, ultrices pretium est. Duis egestas nisi scelerisque vulputate imperdiet. Donec a arcu eu sem hendrerit semper in eu sem. In ultrices metus vel ultricies vulputate. Curabitur blandit rutrum dignissim. Sed molestie blandit risus vitae venenatis. Nulla a semper diam. Fusce tempor sapien faucibus ante finibus, a aliquam nisi tincidunt.

Nunc tincidunt, diam a sodales lacinia, lorem nunc suscipit elit, vitae malesuada nisl sem eu velit. Maecenas dictum ac erat at aliquam. Donec cursus est non risus molestie, sollicitudin laoreet nisl pretium. Ut venenatis finibus leo a pharetra. In urna elit, dictum eu ante et, congue ullamcorper ipsum. Cras cursus sollicitudin enim, sed cursus magna volutpat at. Quisque in erat in justo placerat luctus. Sed a iaculis eros. Nunc et leo tellus. Aliquam erat volutpat. In vestibulum lobortis mollis. Etiam euismod vel nibh a bibendum. Donec ac odio sit amet nunc viverra imperdiet. Vivamus semper porta posuere. Phasellus vestibulum dictum ex, vitae vestibulum libero commodo elementum. Morbi justo risus, elementum et est et, tempus tempus dolor.

Suspendisse vel sapien a lectus luctus pretium vel ac nibh. Sed facilisis nunc non neque tempor pharetra. Mauris ut sapien ipsum. Integer mollis turpis vestibulum metus scelerisque, eget mattis erat volutpat. Vivamus aliquet sodales maximus. Donec feugiat diam quis blandit aliquam. Curabitur semper vitae ligula at ultrices. Vestibulum at tristique leo. In consectetur ante ac ante aliquet, vitae molestie odio vulputate. Praesent nisi nisl, accumsan ut lacus a, imperdiet molestie libero. Ut pulvinar est lacus, lobortis ornare libero condimentum nec.

Aliquam non est vitae neque tristique aliquet id et sapien. Quisque cursus velit a ante faucibus, ut lobortis tellus dictum. Pellentesque suscipit urna enim, sit amet pretium nisi mattis sed. Sed ante erat, tempor sit amet condimentum et, viverra vel lorem. Suspendisse sagittis ligula id mi congue, sit amet commodo augue eleifend. Cras eu aliquam lectus. Praesent porta fringilla tellus, vitae dignissim risus pellentesque id. Nulla facilisis lobortis massa quis cursus. Pellentesque pellentesque, neque sit amet commodo accumsan, ante mauris dignissim orci, non dictum dolor ligula eget leo.

Nunc quis fermentum turpis. Etiam vestibulum dapibus placerat. Phasellus bibendum libero vel metus suscipit, ac molestie urna fringilla. Nam nec vulputate diam. Donec malesuada molestie tempor. Morbi elementum ultricies diam ut molestie. Duis a lorem vestibulum, molestie leo sit amet, laoreet odio. Nullam tincidunt condimentum dolor sit amet mattis. Suspendisse eget tincidunt dolor, vitae tempus mauris. Morbi porta imperdiet risus, vel hendrerit ex ornare eu. Aliquam vitae dolor sagittis, bibendum sapien a, euismod ante. Phasellus ullamcorper massa sit amet elementum rutrum. Mauris vel purus scelerisque, rutrum odio sit amet, accumsan ligula. Donec molestie libero nec quam suscipit egestas.

Nam imperdiet odio quis ex mattis venenatis. Nullam feugiat venenatis posuere. Fusce nec feugiat mauris. Etiam accumsan metus convallis feugiat aliquet. Integer id tortor tempor, maximus ipsum vel, dictum justo. Donec tempus nunc sit amet efficitur posuere. Aliquam non urna nec diam aliquam congue. Vestibulum tellus arcu, vulputate a orci at, porta hendrerit est. In vel lacinia neque. Donec bibendum aliquam consequat. Nulla quis massa ac quam hendrerit accumsan. Duis ut malesuada dolor, nec luctus est. Duis sed mauris risus. Sed viverra non arcu eu commodo.

Nam orci purus, auctor id euismod et, sodales eu mauris. In neque nisl, luctus pellentesque odio at, euismod dictum ante. Nullam laoreet lectus convallis lectus varius posuere. Vestibulum in erat volutpat, sagittis mauris at, sagittis justo. Fusce eu erat convallis, molestie arcu in, luctus neque. Donec congue dui nec nulla cursus mollis. Suspendisse dignissim tortor in libero luctus blandit. Sed nec sapien tristique, pellentesque sapien at, pretium velit. Sed vestibulum eros auctor nisi elementum, vel dictum dolor volutpat. Aliquam rutrum in nulla at efficitur. Maecenas egestas vestibulum nisi. Integer mauris nulla, ultrices quis felis non, varius condimentum sem. Fusce eu iaculis enim, lobortis consequat arcu. Maecenas vehicula non lectus interdum ultrices. In hac habitasse platea dictumst. Maecenas eu laoreet tellus, dictum ornare sapien.

Mauris rhoncus placerat lorem vitae porta. Suspendisse est est, blandit ut risus in, ornare sagittis elit. Donec blandit mollis turpis. Donec molestie convallis felis eu condimentum. Nam ultricies, augue sed rhoncus dictum, justo urna ultrices metus, eget faucibus nulla ipsum quis ipsum. Vestibulum dictum urna semper est porta malesuada. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a vulputate ante, convallis dignissim elit. Fusce felis ante, tristique in leo bibendum, suscipit lacinia orci.

Nullam lobortis condimentum fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur et tortor vitae dolor mattis efficitur quis eu lectus. Proin ut justo odio. Suspendisse placerat gravida luctus. Donec auctor nulla id ante hendrerit sollicitudin. Cras quis dolor egestas, fringilla nisi eget, laoreet enim. Nunc ut ex vestibulum, gravida dui at, rutrum orci. Donec nec magna eu nunc tincidunt cursus scelerisque at neque. Morbi mauris massa, luctus in nibh ut, pretium efficitur sem.

Aenean quis augue efficitur, dapibus eros eget, accumsan tellus. Donec porta risus ut eros ullamcorper, dignissim tincidunt urna varius. Pellentesque viverra risus purus, ut interdum dolor commodo quis. Fusce vel purus purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus placerat vestibulum facilisis. Integer sit amet erat et diam feugiat aliquet eget non magna. Suspendisse id nisi felis. Integer et sapien libero. Suspendisse ac facilisis felis. Maecenas sit amet hendrerit mauris. Ut ex eros, scelerisque ac nisl id, molestie vestibulum sapien. Fusce consectetur sapien in ex sodales, ac ultrices sapien tincidunt.

Suspendisse eget nulla nec tortor consequat sodales eu et ante. Ut scelerisque convallis lacus, non tempor augue tempor id. Ut congue sodales congue. Vestibulum at ante id lacus hendrerit accumsan at eu ligula. Nam consequat facilisis nulla et tincidunt. Duis dictum a enim id pretium. In volutpat eu ex eu pulvinar. Praesent luctus, mauris quis molestie venenatis, ligula massa rutrum nisl, ac sodales lorem mi quis odio. In in molestie felis, in pharetra lectus. Vivamus vel lorem leo. Morbi ut placerat lectus, id blandit magna.

Duis lacinia purus at elit ullamcorper semper. Cras vitae efficitur nibh. Donec condimentum orci turpis, ut fermentum mauris tempus ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse at finibus mi, vel pellentesque metus. Curabitur aliquam interdum faucibus. Proin sit amet risus in libero pretium placerat. Nam eu lorem sit amet tortor consectetur ultrices.

Suspendisse potenti. Sed malesuada nisl non libero venenatis viverra. Duis maximus auctor elit ut porttitor. Duis eget finibus lacus. Fusce vehicula hendrerit nibh, ut consequat elit accumsan quis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed blandit, purus ac auctor ultrices, erat quam tempus tortor, facilisis finibus est orci non sem. Sed bibendum ac nisi vitae tincidunt. Integer porttitor tristique dui vitae mattis. Sed fringilla sem eget feugiat suscipit.

Maecenas id nulla nec erat semper sodales ut eget ante. Sed lacinia dapibus metus, id placerat nibh porttitor lacinia. Cras non nisl tellus. Morbi venenatis nunc nec elit ornare porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer egestas lorem tellus. Quisque mauris lectus, dictum eu turpis id, ultrices consequat mauris. Aliquam id viverra augue, nec dapibus lacus. Fusce mollis ante sed venenatis rutrum.

Morbi neque sem, vestibulum id blandit a, tempor eget dolor. Vestibulum nec nisi euismod nulla sagittis vestibulum vitae nec urna. Nullam id faucibus nisi. Sed euismod lectus arcu, sit amet cursus dolor facilisis ut. Curabitur vel eros ac risus mattis consectetur. Aliquam consequat ac diam vel feugiat. Ut euismod odio in lectus rhoncus, vitae ultricies nunc fermentum. Fusce consectetur at elit mollis rutrum. Etiam vel justo eget mauris maximus sagittis. Maecenas pretium egestas justo a ultricies. Cras finibus ante risus, sed imperdiet risus dictum non.

Vivamus tortor mi, pretium quis dictum nec, porttitor ut nisl. Duis ornare quam eu erat vulputate imperdiet. Proin sodales nulla at justo gravida imperdiet. Cras ullamcorper justo vitae dignissim vulputate. Mauris dignissim varius ligula, id eleifend dui dictum eu. Nunc id laoreet magna, bibendum commodo dui. Nunc sed tortor nec nisi interdum lacinia. Quisque eu mattis sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur ut elit eget lacus sodales porta. Fusce posuere magna tortor, a tempor mauris rhoncus ut. Donec condimentum mi ex.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque velit enim, aliquet consectetur neque id, congue condimentum arcu. Donec at velit eleifend, pharetra velit in, dignissim justo. Mauris interdum justo ac dignissim consequat. Integer semper rhoncus felis. Integer pharetra, mauris eu sollicitudin pretium, ligula diam cursus tortor, sit amet sollicitudin ante libero quis nibh. Quisque vel quam massa. Aenean porta nulla at nulla ultricies, ac condimentum libero pharetra. Quisque elementum auctor tortor, vitae auctor ligula laoreet ac. Integer accumsan varius nisl, aliquam lobortis diam rhoncus vitae. Nunc pharetra tellus eu mauris tristique, et aliquet ipsum fringilla. Sed molestie ornare tortor, et blandit massa suscipit at. Nulla sodales lacus lectus, vitae consequat ipsum vehicula euismod. Cras porttitor lectus lectus, in fermentum metus tempor sed.
"""



start_time = time.time()
if "<math>" in txt:
    end_time = time.time()
    print(end_time - start_time)
end_time = time.time()
print(end_time - start_time)

if txt.find("<math>") != -1:
    end_time = time.time()
    print(end_time - start_time)
end_time = time.time()
print(end_time - start_time)